version: "3.7"

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
networks:
  backend:
