spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/diviction
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: jinjooone123!
